<div align="center">

# CADETX VIRTUAL WORK EXPERIENCE

## SPRINT 1 DATA PROFILING FINDINGS

</div>

### Merged Tables Profiling

**Project:** Heavy Supplier, Inventory & Warehouse Analytics  
**Prepared by:** Keren Oyem  
**Role:** Data Analyst  
**Task:** S1-12

### Master Tables: 
* branches
* products
* inventory_master
* suppliers
* customers
### Sales and Finance Tables: 
* sales_orders_header
* sales_orders_lines
* invoices
* payments
### Procurement and Stock Tables: 
* purchase_orders_header
* purchase_orders_lines
* stock_ledger

## 1. Purpose and Scope

The purpose of this data profiling exercise is to examine the structure, completeness, and basic quality of the datasets provided for the Heavy Supplier, Inventory & Warehouse Analytics project.

The profiling covers 12 tables relating to branches, products, inventory, suppliers, customers, invoices, payments, purchase orders, sales orders, and stock movements.

The assessment focuses on:

- Number of rows and columns in each table.
- Missing values.
- Duplicate row patterns.
- Data types and potential data standardisation requirements.
- Data quality checks that should be completed before further analysis.

The findings will support subsequent data cleaning, validation, data modelling, and KPI development.

**Important:** This report distinguishes confirmed profiling results from additional validation checks that have not yet been completed.

#### Connecting to Warehouse

In [1]:
import duckdb  
import pandas as pd 

con = duckdb.connect("warehouse.duckdb")

In [6]:
con.execute("SHOW TABLES").df()

                      name
0                 branches
1                customers
2         inventory_master
3                 invoices
4                 payments
5                 products
6   purchase_orders_header
7    purchase_orders_lines
8      sales_orders_header
9       sales_orders_lines
10            stock_ledger
11               suppliers

In [14]:
# Profiling all tables
# Create a profiling function   
def profile_table(con, table_name): 
    schema = con.execute( 
        f'DESCRIBE "{table_name}"' 
    ).df() 
 
    row_count = con.execute( 
        f'SELECT COUNT(*) FROM "{table_name}"' 
    ).fetchone()[0] 
 
    duplicate_rows = con.execute(f""" 
        SELECT COUNT(*) 
        FROM ( 
            SELECT * 
            FROM "{table_name}" 
            GROUP BY ALL 
            HAVING COUNT(*) > 1 
        ) AS duplicates 
    """).fetchone()[0] 
 
    missing_values = {} 
 
    for column in schema["column_name"]: 
        query = f''' 
 
            SELECT COUNT(*) - COUNT("{column}") 
            FROM "{table_name}" 
        ''' 
 
        missing_values[column] = con.execute( 
            query 
        ).fetchone()[0] 
 
    return { 
        "table_name": table_name, 
        "row_count": row_count, 
        "column_count": len(schema), 
        "schema": schema, 
        "missing_values": missing_values, 
        "duplicate_rows": duplicate_rows 
    }

#### Creating a Variable to Store all Tables

In [13]:
all_tables = [ 
    "branches", 
    "products", 
    "inventory_master",
    "suppliers",
    "customers",
    "invoices",
    "payments",
    "purchase_orders_header",
    "purchase_orders_lines",
    "sales_orders_header",
    "sales_orders_lines",
    "stock_ledger"
    
] 
 
for table in all_tables: 
    result = profile_table(con, table) 
 
    print("\nTable:", result["table_name"]) 
    print("Rows:", result["row_count"]) 
    print("Columns:", result["column_count"]) 
    print("Missing values:", result["missing_values"])
    print("Duplicate row patterns:", 
result["duplicate_rows"])
 
    display(result["schema"])

Table: branches
Rows: 6
Columns: 13
Missing values: {'branch_id': 0, 'branch_name': 0, 'city': 0, 'state': 0, 'region': 0, 'warehouse_type': 0, 'warehouse_capacity': 0, 'service_center_available': 0, 'manager_id': 0, 'total_employees': 0, 'avg_monthly_revenue': 0, 'monthly_operational_cost': 0, 'market_demand_index': 0}
Duplicate row patterns: 0

                 column_name column_type null   key default extra
0                  branch_id     VARCHAR  YES  None    None  None
1                branch_name     VARCHAR  YES  None    None  None
2                       city     VARCHAR  YES  None    None  None
3                      state     VARCHAR  YES  None    None  None
4                     region     VARCHAR  YES  None    None  None
5             warehouse_type     VARCHAR  YES  None    None  None
6         warehouse_capacity     VARCHAR  YES  None    None  None
7   service_center_available     BOOLEAN  YES  None    None  None
8                 manager_id      BIGINT  YES  None    None  None
9            total_employees      BIGINT  YES  None    None  None
10       avg_monthly_revenue      BIGINT  YES  None    None  None
11  monthly_operational_cost      BIGINT  YES  None    None  None
12       market_demand_index      BIGINT  YES  None    None  None

Table: products
Rows: 30
Columns: 23
Missing values: {'product_id': 0, 'product_name': 0, 'category': 0, 'machine_type': 0, 'brand': 0, 'model_compatibility': 0, 'unit_cost': 0, 'unit_price': 0, 'margin_percentage': 0, 'gst_rate': 0, 'weight_kg': 0, 'dimensions_cm': 0, 'material_type': 0, 'warranty_months': 0, 'reorder_level': 0, 'safety_stock': 0, 'max_stock_level': 0, 'lead_time_days': 0, 'criticality_level': 0, 'usage_frequency': 0, 'uom': 0, 'last_purchase_price': 0, 'last_purchase_date': 0}
Duplicate row patterns: 0

            column_name column_type null   key default extra
0            product_id     VARCHAR  YES  None    None  None
1          product_name     VARCHAR  YES  None    None  None
2              category     VARCHAR  YES  None    None  None
3          machine_type     VARCHAR  YES  None    None  None
4                 brand     VARCHAR  YES  None    None  None
5   model_compatibility     VARCHAR  YES  None    None  None
6             unit_cost      BIGINT  YES  None    None  None
7            unit_price      BIGINT  YES  None    None  None
8     margin_percentage      DOUBLE  YES  None    None  None
9              gst_rate      BIGINT  YES  None    None  None
10            weight_kg      DOUBLE  YES  None    None  None
11        dimensions_cm     VARCHAR  YES  None    None  None
12        material_type     VARCHAR  YES  None    None  None
13      warranty_months      BIGINT  YES  None    None  None
14        reorder_level      BIGINT  YES  None    None  None
15         safety_stock      BIGINT  YES  None    None  None
16      max_stock_level      BIGINT  YES  None    None  None
17       lead_time_days      BIGINT  YES  None    None  None
18    criticality_level     VARCHAR  YES  None    None  None
19      usage_frequency     VARCHAR  YES  None    None  None
20                  uom     VARCHAR  YES  None    None  None
21  last_purchase_price      BIGINT  YES  None    None  None
22   last_purchase_date        DATE  YES  None    None  None

Table: inventory_master
Rows: 180
Columns: 8
Missing values: {'product_id': 0, 'branch_id': 0, 'opening_stock': 0, 'reorder_level': 0, 'safety_stock': 0, 'max_stock': 0, 'current_stock': 0, 'warehouse_bin': 0}
Duplicate row patterns: 0

     column_name column_type null   key default extra
0     product_id     VARCHAR  YES  None    None  None
1      branch_id     VARCHAR  YES  None    None  None
2  opening_stock      BIGINT  YES  None    None  None
3  reorder_level      BIGINT  YES  None    None  None
4   safety_stock      BIGINT  YES  None    None  None
5      max_stock      BIGINT  YES  None    None  None
6  current_stock      BIGINT  YES  None    None  None
7  warehouse_bin     VARCHAR  YES  None    None  None

Table: suppliers
Rows: 8
Columns: 12
Missing values: {'supplier_id': 0, 'supplier_name': 0, 'supplier_type': 0, 'product_category': 0, 'city': 0, 'province': 0, 'region': 0, 'pincode': 0, 'lead_time_days': 0, 'reliability_score': 0, 'import_duty_rate': 0, 'china_tax_id': 0}
Duplicate row patterns: 0

          column_name column_type null   key default extra
0         supplier_id     VARCHAR  YES  None    None  None
1       supplier_name     VARCHAR  YES  None    None  None
2       supplier_type     VARCHAR  YES  None    None  None
3    product_category     VARCHAR  YES  None    None  None
4                city     VARCHAR  YES  None    None  None
5            province     VARCHAR  YES  None    None  None
6              region     VARCHAR  YES  None    None  None
7             pincode      BIGINT  YES  None    None  None
8      lead_time_days      BIGINT  YES  None    None  None
9   reliability_score      BIGINT  YES  None    None  None
10   import_duty_rate      BIGINT  YES  None    None  None
11       china_tax_id     VARCHAR  YES  None    None  None

Table: customers
Rows: 500
Columns: 15
Missing values: {'customer_id': 0, 'customer_type': 0, 'industry_segment': 0, 'city': 0, 'state': 0, 'pincode': 0, 'region': 0, 'branch_id': 0, 'credit_limit': 0, 'current_balance': 0, 'payment_terms': 0, 'customer_since': 0, 'last_purchase_date': 0, 'total_purchase_value': 0, 'customer_rating': 0}
Duplicate row patterns: 0

             column_name column_type null   key default extra
0            customer_id     VARCHAR  YES  None    None  None
1          customer_type     VARCHAR  YES  None    None  None
2       industry_segment     VARCHAR  YES  None    None  None
3                   city     VARCHAR  YES  None    None  None
4                  state     VARCHAR  YES  None    None  None
5                pincode      BIGINT  YES  None    None  None
6                 region     VARCHAR  YES  None    None  None
7              branch_id     VARCHAR  YES  None    None  None
8           credit_limit      BIGINT  YES  None    None  None
9        current_balance      BIGINT  YES  None    None  None
10         payment_terms     VARCHAR  YES  None    None  None
11        customer_since        DATE  YES  None    None  None
12    last_purchase_date        DATE  YES  None    None  None
13  total_purchase_value      BIGINT  YES  None    None  None
14       customer_rating      BIGINT  YES  None    None  None

Table: invoices
Rows: 18033
Columns: 10
Missing values: {'invoice_id': 0, 'so_id': 0, 'customer_id': 0, 'branch_id': 0, 'invoice_date': 0, 'due_date': 0, 'total_order_value': 0, 'total_gst_amount': 0, 'grand_total': 0, 'payment_status': 0}
Duplicate row patterns: 0

         column_name column_type null   key default extra
0         invoice_id     VARCHAR  YES  None    None  None
1              so_id     VARCHAR  YES  None    None  None
2        customer_id     VARCHAR  YES  None    None  None
3          branch_id     VARCHAR  YES  None    None  None
4       invoice_date        DATE  YES  None    None  None
5           due_date        DATE  YES  None    None  None
6  total_order_value      BIGINT  YES  None    None  None
7   total_gst_amount      DOUBLE  YES  None    None  None
8        grand_total      DOUBLE  YES  None    None  None
9     payment_status     VARCHAR  YES  None    None  None

Table: payments
Rows: 19257
Columns: 5
Missing values: {'payment_id': 0, 'invoice_id': 0, 'payment_date': 0, 'payment_amount': 0, 'payment_method': 0}
Duplicate row patterns: 0

      column_name column_type null   key default extra
0      payment_id     VARCHAR  YES  None    None  None
1      invoice_id     VARCHAR  YES  None    None  None
2    payment_date        DATE  YES  None    None  None
3  payment_amount      DOUBLE  YES  None    None  None
4  payment_method     VARCHAR  YES  None    None  None

Table: purchase_orders_header
Rows: 24000
Columns: 10
Missing values: {'po_id': 0, 'supplier_id': 0, 'branch_id': 0, 'order_date': 0, 'expected_delivery_date': 0, 'received_date': 2370, 'po_status': 0, 'total_cost': 0, 'total_gst_amount': 0, 'grand_total': 0}
Duplicate row patterns: 0

              column_name column_type null   key default extra
0                   po_id     VARCHAR  YES  None    None  None
1             supplier_id     VARCHAR  YES  None    None  None
2               branch_id     VARCHAR  YES  None    None  None
3              order_date        DATE  YES  None    None  None
4  expected_delivery_date        DATE  YES  None    None  None
5           received_date        DATE  YES  None    None  None
6               po_status     VARCHAR  YES  None    None  None
7              total_cost      DOUBLE  YES  None    None  None
8        total_gst_amount      DOUBLE  YES  None    None  None
9             grand_total      DOUBLE  YES  None    None  None

Table: purchase_orders_lines
Rows: 155495
Columns: 9
Missing values: {'po_id': 0, 'line_number': 0, 'product_id': 0, 'quantity': 0, 'unit_cost': 0, 'gst_rate': 0, 'line_total': 0, 'gst_amount': 0, 'line_grand_total': 0}
Duplicate row patterns: 0

        column_name column_type null   key default extra
0             po_id     VARCHAR  YES  None    None  None
1       line_number      BIGINT  YES  None    None  None
2        product_id     VARCHAR  YES  None    None  None
3          quantity      BIGINT  YES  None    None  None
4         unit_cost      DOUBLE  YES  None    None  None
5          gst_rate      BIGINT  YES  None    None  None
6        line_total      DOUBLE  YES  None    None  None
7        gst_amount      DOUBLE  YES  None    None  None
8  line_grand_total      DOUBLE  YES  None    None  None

Table: sales_orders_header
Rows: 20000
Columns: 11
Missing values: {'so_id': 0, 'customer_id': 0, 'branch_id': 0, 'order_date': 0, 'delivery_date': 0, 'order_status': 0, 'payment_terms': 0, 'total_order_value': 0, 'total_gst_amount': 0, 'grand_total': 0, 'sales_channel': 0}
Duplicate row patterns: 0

          column_name column_type null   key default extra
0               so_id     VARCHAR  YES  None    None  None
1         customer_id     VARCHAR  YES  None    None  None
2           branch_id     VARCHAR  YES  None    None  None
3          order_date        DATE  YES  None    None  None
4       delivery_date        DATE  YES  None    None  None
5        order_status     VARCHAR  YES  None    None  None
6       payment_terms     VARCHAR  YES  None    None  None
7   total_order_value      BIGINT  YES  None    None  None
8    total_gst_amount      DOUBLE  YES  None    None  None
9         grand_total      DOUBLE  YES  None    None  None
10      sales_channel     VARCHAR  YES  None    None  None

Table: sales_orders_lines
Rows: 130402
Columns: 9
Missing values: {'so_id': 0, 'line_number': 0, 'product_id': 0, 'quantity': 0, 'unit_price': 0, 'gst_rate': 0, 'line_total': 0, 'gst_amount': 0, 'line_grand_total': 0}
Duplicate row patterns: 0

        column_name column_type null   key default extra
0             so_id     VARCHAR  YES  None    None  None
1       line_number      BIGINT  YES  None    None  None
2        product_id     VARCHAR  YES  None    None  None
3          quantity      BIGINT  YES  None    None  None
4        unit_price      BIGINT  YES  None    None  None
5          gst_rate      BIGINT  YES  None    None  None
6        line_total      BIGINT  YES  None    None  None
7        gst_amount      DOUBLE  YES  None    None  None
8  line_grand_total      DOUBLE  YES  None    None  None

Table: stock_ledger
Rows: 237230
Columns: 9
Missing values: {'movement_id': 0, 'product_id': 0, 'branch_id': 0, 'movement_type': 0, 'movement_date': 0, 'quantity': 0, 'reference_type': 0, 'reference_id': 0, 'running_balance': 0}
Duplicate row patterns: 0

       column_name column_type null   key default extra
0      movement_id     VARCHAR  YES  None    None  None
1       product_id     VARCHAR  YES  None    None  None
2        branch_id     VARCHAR  YES  None    None  None
3    movement_type     VARCHAR  YES  None    None  None
4    movement_date        DATE  YES  None    None  None
5         quantity      BIGINT  YES  None    None  None
6   reference_type     VARCHAR  YES  None    None  None
7     reference_id     VARCHAR  YES  None    None  None
8  running_balance      BIGINT  YES  None    None  None

## 2. Table-Level Profiling Results

### 2.1 Branches

**Table name:** `branches`

**Profile:**
- Rows: 6
- Columns: 13
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains branch information, including identifiers, warehouse capacity, service centre availability, employee counts, and financial or market-related fields.

The `warehouse_capacity` column is stored as `VARCHAR`. This requires review to determine whether the capacity values should be converted into a numeric format with a consistent unit of measurement.

Several numeric fields, including `manager_id`, employee counts, revenue, cost, and market index, are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that each branch has a unique identifier.
- Review `warehouse_capacity` for consistent units and numeric convertibility.
- Validate employee counts and financial values.
- Check that service centre availability is consistently represented.

---

### 2.2 Products

**Table name:** `products`

**Profile:**
- Rows: 30
- Columns: 23
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains product attributes, including product identifiers, dimensions, weight, margin percentage, and purchase-related dates.

The `dimensions_cm` column is stored as `VARCHAR`, while `margin_percentage` and `weight_kg` are stored as `DOUBLE`. The `last_purchase_date` column is stored as `DATE`.

Several other numeric fields are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that product identifiers are unique.
- Standardise the format of `dimensions_cm`.
- Check whether dimensions can be separated into length, width, and height.
- Validate that product weights and margins contain reasonable values.
- Review date fields for consistency with the relevant business rules.
- Confirm that product categories and other descriptive fields use consistent labels.

---

### 2.3 Inventory Master

**Table name:** `inventory_master`

**Profile:**
- Rows: 180
- Columns: 8
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains inventory-related identifiers, bin information, and stock quantities.

Identifiers and bin-related fields are stored as `VARCHAR`, while stock quantity fields are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm the uniqueness of inventory identifiers or the appropriate composite keys.
- Check that product and branch references correspond to valid records in their respective tables.
- Review stock quantities for negative or otherwise unexpected values.
- Confirm that bin identifiers follow a consistent format.
- Compare inventory balances with relevant stock ledger records where the business rules permit.

---

### 2.4 Suppliers

**Table name:** `suppliers`

**Profile:**
- Rows: 8
- Columns: 12
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains supplier information, including identifiers, lead time, reliability score, import duty rate, and postal information.

The `pincode` column is stored as `BIGINT`. This should be reviewed because postal codes are identifiers rather than quantities, and a text data type may be more appropriate for preserving leading zeros and supporting consistent formatting.

The `lead_time_days`, `reliability_score`, and `import_duty_rate` columns are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that supplier identifiers are unique.
- Review postal code formatting and consider converting `pincode` to a suitable text type.
- Validate lead times and reliability scores against the expected business ranges.
- Confirm that import duty rates use a consistent representation.
- Check supplier references in purchase order records.

---

### 2.5 Customers

**Table name:** `customers`

**Profile:**
- Rows: 500
- Columns: 15
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains customer information, including customer identifiers, postal codes, customer dates, purchase dates, and other numeric attributes.

The `pincode` column is stored as `BIGINT`, while `customer_since` and `last_purchase_date` are stored as `DATE`.

Several monetary, rating, and other numeric fields are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that customer identifiers are unique.
- Review postal code formatting and consider using a text data type.
- Validate the relationship between `customer_since` and `last_purchase_date`.
- Check that rating and monetary fields follow the expected business rules.
- Validate customer references in sales order and invoice records.

---

### 2.6 Invoices

**Table name:** `invoices`

**Profile:**
- Rows: 18,033
- Columns: 10
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains invoice dates, due dates, invoice values, GST amounts, and grand totals.

The `invoice_date` and `due_date` columns are stored as `DATE`. The `total_order_value` column is stored as `BIGINT`, while `total_gst_amount` and `grand_total` are stored as `DOUBLE`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that invoice identifiers are unique.
- Check that invoice dates and due dates follow the expected chronological rules.
- Validate invoice references to the appropriate customers or orders.
- Reconcile invoice totals, GST amounts, and grand totals using the applicable calculation rules.
- Compare invoice amounts with related payment records.
- Check for invoices that have no corresponding order or other required business record.

---

### 2.7 Payments

**Table name:** `payments`

**Profile:**
- Rows: 19,257
- Columns: 5
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains payment-related information, including payment dates and payment amounts.

The `payment_date` column is stored as `DATE`, while `payment_amount` is stored as `DOUBLE`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm the uniqueness of payment identifiers.
- Check that payment amounts follow the expected business rules.
- Validate payment references to invoices.
- Compare total payments against invoice balances where appropriate.
- Investigate payments that cannot be matched to a valid invoice.
- Review whether multiple payments against one invoice are permitted under the business rules.

---

### 2.8 Purchase Orders Header

**Table name:** `purchase_orders_header`

**Profile:**
- Rows: 24,000
- Columns: 10
- Missing values: 2,370 in `received_date`
- Duplicate row patterns: 0

**Data type observations:**

The table contains purchase order header information, including dates and financial values.

Date fields are stored as `DATE`, while financial fields are stored as `DOUBLE`.

**Data quality findings:**

The `received_date` column contains 2,370 missing values. This is the only confirmed missing-value issue identified in the initial profiling of the 12 tables.

The missing values require investigation because they may represent purchase orders that have not yet been received, orders that were cancelled, or incomplete records. These possibilities have not yet been confirmed.

**Recommended validation:**

- Investigate the 2,370 missing `received_date` values.
- Determine whether the missing dates are valid for open, pending, or cancelled purchase orders.
- Avoid automatically filling missing dates without understanding their meaning.
- Confirm that purchase order identifiers are unique.
- Validate supplier references.
- Check order dates and received dates for chronological consistency.
- Reconcile purchase order header values with the corresponding purchase order line records.

---

### 2.9 Purchase Orders Lines

**Table name:** `purchase_orders_lines`

**Profile:**
- Rows: 155,495
- Columns: 9
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains purchase order line information, including line numbers, quantities, GST rates, and financial values.

The `line_number`, `quantity`, and `gst_rate` columns are stored as `BIGINT`. Monetary and calculated fields are stored as `DOUBLE`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Check the uniqueness of purchase order line identifiers or composite keys.
- Confirm that each line references a valid purchase order.
- Validate quantities and unit prices.
- Check that GST rates use a consistent representation.
- Recalculate line totals and GST amounts using the applicable business rules.
- Reconcile purchase order line totals with the purchase order header totals.

---

### 2.10 Sales Orders Header

**Table name:** `sales_orders_header`

**Profile:**
- Rows: 20,000
- Columns: 11
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains sales order header information, including order dates, delivery dates, order values, GST amounts, and grand totals.

The `order_date` and `delivery_date` columns are stored as `DATE`. The `total_order_value` column is stored as `BIGINT`, while GST and grand total fields are stored as `DOUBLE`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm that sales order identifiers are unique.
- Validate customer and branch references.
- Check the relationship between order dates and delivery dates.
- Reconcile sales order header values against the corresponding sales order lines.
- Validate GST amounts and grand totals.
- Investigate orders without corresponding line records where line records are required.

---

### 2.11 Sales Orders Lines

**Table name:** `sales_orders_lines`

**Profile:**
- Rows: 130,402
- Columns: 9
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains sales order line information, including line numbers, quantities, unit prices, GST rates, line totals, GST amounts, and line grand totals.

The `line_number`, `quantity`, `unit_price`, `gst_rate`, and `line_total` columns are stored as `BIGINT`. The `gst_amount` and `line_grand_total` columns are stored as `DOUBLE`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Check the uniqueness of sales order line identifiers or composite keys.
- Confirm that every sales order line references a valid sales order.
- Validate product references.
- Review whether `unit_price` and `line_total` should support decimal values.
- Recalculate line totals, GST amounts, and line grand totals.
- Reconcile line-level values against sales order header totals.

---

### 2.12 Stock Ledger

**Table name:** `stock_ledger`

**Profile:**
- Rows: 237,230
- Columns: 9
- Missing values: None
- Duplicate row patterns: 0

**Data type observations:**

The table contains stock movement information, including movement dates, quantities, and running balances.

The `movement_date` column is stored as `DATE`, while `quantity` and `running_balance` are stored as `BIGINT`.

**Data quality findings:**

No missing values or duplicate row patterns were identified during the initial profiling.

**Recommended validation:**

- Confirm the uniqueness of stock movement identifiers or the appropriate composite keys.
- Validate product and branch references.
- Check whether stock movement quantities follow the expected rules for each movement type.
- Review running balances for consistency with preceding balances and recorded movements.
- Investigate unexpected negative balances.
- Compare stock ledger balances with inventory master quantities where the business rules permit.

## 3. Cross-Table Data Quality Observations

### 3.1 Missing Values

The initial profiling identified missing values in only one table:

| Table | Column | Missing Values |
|---|---|---:|
| `purchase_orders_header` | `received_date` | 2,370 |

All other profiled tables had no missing values in the columns examined.

The missing `received_date` values should be investigated before deciding whether they should remain missing, be corrected, or be treated as valid business exceptions.

### 3.2 Duplicate Row Patterns

The initial profiling reported zero duplicate row patterns in all 12 tables.

However, the absence of identical duplicate rows does not guarantee that all primary keys or business keys are unique. Separate checks should be performed on identifiers and composite keys.

### 3.3 Data Type Standardisation

Several columns require review before the data is used for analysis.

| Table | Column | Current Data Type | Recommended Review |
|---|---|---|---|
| `branches` | `warehouse_capacity` | `VARCHAR` | Confirm units and numeric format |
| `products` | `dimensions_cm` | `VARCHAR` | Standardise dimension format |
| `suppliers` | `pincode` | `BIGINT` | Consider text to preserve formatting |
| `customers` | `pincode` | `BIGINT` | Consider text to preserve formatting |
| `sales_orders_lines` | `unit_price` | `BIGINT` | Confirm whether decimal precision is required |
| `sales_orders_lines` | `line_total` | `BIGINT` | Confirm whether decimal precision is required |

These observations identify columns for review. They do not, by themselves, establish that the stored values are incorrect.

### 3.4 Referential Integrity

The dataset contains related tables for branches, products, inventory, suppliers, customers, purchase orders, sales orders, invoices, payments, and stock movements.

Foreign key validation is required to confirm that references between these tables are valid.

The initial profiling results do not establish whether any foreign key violations exist.

### 3.5 Financial Reconciliation

The purchase order, sales order, invoice, and payment tables contain related financial information.

Additional checks should confirm that:
- Line totals agree with the applicable quantity and unit price calculations.
- GST amounts follow the appropriate tax calculation rules.
- Grand totals agree with the relevant base amounts and GST.
- Header totals reconcile with their corresponding line records.
- Payments can be matched to invoices and reconciled against outstanding balances.

These checks remain pending unless separately performed and documented.

### 3.6 Date Consistency

Date columns are present across several tables, including customers, invoices, payments, purchase orders, sales orders, and stock ledger records.

Additional checks should verify chronological consistency, including order dates, delivery dates, invoice dates, due dates, received dates, and payment dates where applicable.

No date inconsistency is confirmed by the initial profiling results alone.

## 4. Key Findings

The initial data profiling exercise produced the following findings:

1. **Twelve tables were profiled** across the supplier, product, inventory, warehouse, customer, order, invoice, payment, and stock movement areas.

2. **Missing values were identified in one table.** The `received_date` column in `purchase_orders_header` contains 2,370 missing values.

3. **No duplicate row patterns were reported** in any of the 12 tables during the initial profiling.

4. **Potential data type standardisation requirements were identified.** These include warehouse capacity, product dimensions, postal codes, and sales line financial fields.

5. **Additional validation is required** before the data can be considered fully ready for analysis. Important checks include key uniqueness, referential integrity, financial reconciliation, date consistency, and stock balance validation.

6. **The profiling results provide a foundation for subsequent project tasks**, including data cleaning, data modelling, KPI calculation, and dashboard development.

---

## 5. Recommended Actions

The following actions are recommended before proceeding to advanced analysis.

| Priority | Action | Reason |
|---|---|---|
| High | Investigate missing `received_date` values in `purchase_orders_header` | Determine whether missing dates represent valid business situations or data quality issues |
| High | Validate primary keys and composite keys | Confirm record uniqueness using the appropriate business identifiers |
| High | Check foreign key relationships | Ensure that related records reference valid entities |
| High | Reconcile purchase and sales order totals | Confirm consistency between header and line-level financial values |
| High | Validate invoice and payment relationships | Support accurate financial reporting |
| Medium | Standardise warehouse capacity and product dimensions | Improve consistency and usability for analysis |
| Medium | Review numeric data types for financial fields | Ensure appropriate precision for monetary calculations |
| Medium | Validate stock ledger movements and running balances | Support inventory accuracy and stock movement analysis |
| Medium | Review date consistency across related tables | Improve the reliability of time-based analysis |
| Medium | Document validation outcomes and cleaning decisions | Maintain transparency and reproducibility |

## 6. Conclusion

The initial profiling of the 12 tables provides an overview of the dataset structure, completeness, duplicate row patterns, and potential data type standardisation requirements.

The most significant confirmed finding is the presence of 2,370 missing values in the `received_date` column of `purchase_orders_header`. No duplicate row patterns were reported in the initial profiling.

Although the initial results show generally complete tables, further validation is necessary to establish whether the data meets the requirements for reliable analysis. The next stage should focus on investigating missing receipt dates, validating keys and relationships, standardising selected data types, reconciling financial values, and checking stock movement consistency.

These steps will help establish a reliable foundation for the project's data modelling, KPI development, and warehouse analytics.

---

**Prepared by:** Keren Oyem  
**Role:** Data Analyst  
**Task:** S1-12  
**Project:** Heavy Supplier, Inventory & Warehouse Analytics  
**Programme:** CADETX Virtual Work Experience

---

### Profiling Note

The row counts, column counts, missing-value counts, duplicate row pattern counts, and stated data types in this report reflect the initial profiling results.

The validation checks and recommended actions are proposed next steps. They should not be interpreted as confirmed data quality errors unless their results are separately tested and documented.